 [[params.social]]
    icon = "linkedin"
    icon_pack = "fa"
    link = "//linkedin.com/in/sooleymanli"

 [[params.social]]
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/sooleymanli"

 [[params.social]]
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/sooleymanli"
